# -*- coding: utf-8 -*-
"""Q2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1gD3S_shqzareI1CGdsuHiyqfrKXYO2JI
"""

# 18 Sep 2023
# CSC461 – Assignment1 – Web Scraping
# Hamna Ashraf
# sp20-bse-047
# This code gives information of important events happened on my birthday and
# shows the name of people i share my birthday with.

import requests
from bs4 import BeautifulSoup

# Define the URL for the "Britannica" website
url_britannica = "https://www.britannica.com/on-this-day/August-17"

# Send an HTTP GET request to the "Britannica" URL with headers
page_britannica = requests.get(url_britannica, headers={"User-Agent": "Mozilla/5.0"})

# Parse the HTML content of the page
soup_britannica = BeautifulSoup(page_britannica.content, "html.parser")

# Find the container div for events
events_container = soup_britannica.find("div", class_="border-top py-30")

# Find all divs containing event details
event_divs = events_container.find_all("div", class_="card-body font-serif")

# Initialize an empty list to store event descriptions
events_descriptions = []

# Iterate through event divs and extract event descriptions
for event_div in event_divs:
    event_description = event_div.text.strip()
    events_descriptions.append(event_description)

# Print the events with proper numbering and formatting
print("Important events on August 17th according to Britannica:\n")
for i, event_description in enumerate(events_descriptions, 1):
    print(f"{i}. {event_description}\n")

# Define the URL for the "timeanddate" website
url_timeanddate = 'https://www.timeanddate.com/on-this-day/august/17'

print("\nI share my birthdate with following people according to 'timeanddate' website:\n")
event_page = requests.get(url_timeanddate, headers={"User-Agent": 'Mozilla/5.0'})
soup_event = BeautifulSoup(event_page.content, "html.parser")

# Find the event block container
event_block = soup_event.find("div", class_="otd-life__block")
event_list = event_block.find("ul")

# Initialize a list to store event names
event_names = []

# Find and extract event names
h3_events = event_list.find_all("h3")
for h3 in h3_events:
    event_name = h3.text.split(" ", 1)[1]
    event_names.append(event_name)
    print(f"- {event_name}\n")